version: '3.8'

x-env: &env
  environment:
    MYSQL_ROOT_PASSWORD: examplepassword
    MYSQL_DATABASE: yourdatabase
    MYSQL_USER: youruser
    MYSQL_PASSWORD: yourpassword

services:
  fastify-server-1:
    <<: *env
    build: ./fastify-server-1
    ports:
      - "3000:3000"

  fastify-server-2:
    build: ./fastify-server-2
    ports:
      - "3001:3001"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - fastify-server-1
      - fastify-server-2

  mariadb:
    <<: *env
    image: mariadb
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql

  # mariadb-maxscale:
  #   build: ./maxscale
  #   ports:
  #     - "3306:3306"
  #     - "8989:8989"
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - maxscale-data:/var/lib/maxscale

volumes:
  mariadb-data:
  # maxscale-data:
